##############################################################
## General Configurations ##
##############################################################
homeassistant:
  name: Home
  latitude: !secret_latitude
  longitude: !secret_longitude
  elevation: 7
  unit_system: imperial
  time_zone: Europe/Madrid

#  customize: !include customize.yaml

frontend:
discovery:
sun:
conversation:
history:
updater:
logbook:
#group: !include group.yaml
http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
  
  ##############################################################
## Integrated Components ##
##############################################################

# Text to speech
tts:
  platform: google

#Dark Sky
sensor 1:
  - platform: darksky
    api_key: 2a04a7d5c2b0a1300d06011521b8af2e
    monitored_conditions:
      - summary
      - icon
      - nearest_storm_distance
      - nearest_storm_bearing
      - precip_type
      - precip_intensity
      - precip_probability
      - temperature
      - apparent_temperature
      - dew_point
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      - pressure
      - visibility
      - ozone
      - minutely_summary
      - hourly_summary
      - daily_summary
      - temperature_max
      - temperature_min
      - apparent_temperature_max
      - apparent_temperature_min
      - precip_intensity_max

#Speedtest.net data for RPi
sensor 2:
  platform: speedtest
  minute:
    - 0
    - 30
  monitored_conditions:
    - ping
    - download
    - upload
   
   #RPi cpu speed
sensor 3:
  platform: cpuspeed
  name: CPU

#RPi cpu data
sensor 4:
  platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: processor_use

#Lifx Lights
light:
  platform: lifx
  broadcast: 192.168.1.255

#Kodi
media_player:
  - platform: kodi
    host: http://192.168.29.239
    name: Living Room
    turn_off_action: quit
      
#kodi notifier
notify:
  - platform: kodi
    name: Living Room
    host: http://192.168.29.239
